from random import random
random()
0.9595266948278349
random(20)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: random() takes no arguments (1 given) 
